### ISSUE TITLE
Link to VOD download on Drive is a 404

### ISSUE THREAD

**Issue by Tylerangers** [TimIsOverpowered/xqc-frontend#13]
When opening the VODs https://xqc.wtf/manual/1730292903 (2/6/2023) and https://xqc.wtf/manual/1732443987 (2/8/2023) The link for the VOD it says 404. That’s an error. The requested URL was not found on this server. That’s all we know.

Any idea why this is happening to this VOD but all the other ones are fine?

**Comment by Bertaz** [comment]
Are those 2 VODs not saved to drive or is the link simply missing from the site @TimIsOverpowered ?

**Comment by TimIsOverpowered** [comment]
https://github.com/TimIsOverpowered/xqc-frontend/issues/20
