### ISSUE TITLE
Search does not retrieve anything and just gives undefined

### ISSUE THREAD

**Issue by Turrt** [TimIsOverpowered/xqc-frontend#15]
I feel like a search for games would also be pretty good

**Comment by Bertaz** [comment]
Search works for the titles, you have to insert the text you want to search for and wait for the drop down menu to appear with a list of matching VODs.

You are correct that there's a bug if you press `Enter`. It turns the inserted text into `undefined`.
It should either do nothing or open a new page with the full list of results for that query

**Comment by TimIsOverpowered** [comment]
https://github.com/TimIsOverpowered/xqc-frontend/commit/8dd12c40c3c3829523c0f24b7927aca26dd0f00d
