### ISSUE TITLE
Most old vod not reupload

### ISSUE THREAD

**Issue by jackthedazzle** [TimIsOverpowered/xqc-frontend#18]
Hey, I been watching a lot old vod since this site launch back at 2022, but why the old any vod not reupload? I hate actually click download button and getting unable to play on google drive. Just hopefully reupload old vod this site again so i can watch again like gta rp game section or something

Thx you

**Comment by Bertaz** [comment]
I imagine you are talking about this "error": ![Unable to play this video at this time. The number of allowed playbacks has been exceeded. Please try again later.
Download](https://github.com/TimIsOverpowered/xqc-frontend/assets/44445647/55900485-51b8-44ef-ba88-a879cd5340e5)
Simply click on the `Download` button under the error, it should open a new page where you should click on `Download anyway`: ![Google Drive can't scan this file for viruses.
file.mp4 (size G) is too large for Google to scan for viruses. Would you still like to download this file?
Download anyway](https://github.com/TimIsOverpowered/xqc-frontend/assets/44445647/af0fabce-9d4f-4b2e-9fbe-731f837356ce)
Then, when the file fully downloaded on your pc, you can go back to the site and press select video: 
![SELECT VIDEO](https://github.com/TimIsOverpowered/xqc-frontend/assets/44445647/798aed34-dc4c-4707-bc4f-045a0154bdcd)
Select the file you just downloaded, the site is gonna play it for you with synchronized chat on the side

**Comment by Bertaz** [comment]
All the VODs seems to be available on the site, I tested the oldest 2, if a specific one is down you have to write which one it is.
If the error is 429 or `Sorry, you can't view or download this file at this time.` <details><summary>Image</summary>
![Sorry, you can't view or download this file at this time.
Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.](https://github.com/TimIsOverpowered/xqc-frontend/assets/44445647/fba7c36b-9c86-4888-8b76-df6ab66e47e5)
</details>

login to google and press this button: ![Add shortcut to Drive](https://github.com/TimIsOverpowered/xqc-frontend/assets/44445647/e5695326-f61a-415c-8044-85d04f0dc3b3), then go in your drive and right click `Download`: ![file.mp4 | Original file
Open with
Download
Share](https://github.com/TimIsOverpowered/xqc-frontend/assets/44445647/21025dd2-e2c1-417c-93b2-a7ca717664c1).
The download should start

**Comment by TimIsOverpowered** [comment]
Most games have been reuploaded
