### ISSUE TITLE
Link to VOD download on Drive is a 404 for the Hogwarts Legacy stream

### ISSUE THREAD

**Issue by TinyWizard4** [TimIsOverpowered/xqc-frontend#19]
Trying to download the VOD for the Hogwarts Legacy stream (https://xqc.wtf/manual/1730292903 (2/6/2023)) gives an 404 error. The button redirects to: https://drive.google.com/u/2/open?id=. So I would assume that the link is missing.

**Comment by TimIsOverpowered** [comment]
Unfortunately it won't be fixed.
