### ISSUE TITLE
Vods will no longer be saved on Drive

### ISSUE THREAD

**Issue by TimIsOverpowered** [TimIsOverpowered/xqc-frontend#20]
Drive is changing their unlimited data storage, so the vods will no longer be backed up and hosted there. As of right now, there is no plans to switch to another provider.

If you still wish to download the vods, please do so until August 4th.

**Comment by Tristar7** [comment]
It is still possible to store enough data at a reasonable price.

You can get more space by adding more users, 5TB per user each for around $20 per month.

With 5+ users it is possible to request more storage from support, 5TB per user every 90 days.

So 25TB every 3 months extra, which should be easily enough to archive multiple streamers for under $100 per month.

You can further drop the cost by "archiving" these extra users, which saves around 2/3, so roughly down to $60 per month total for 5.

**Comment by Spectroxx** [comment]
> It is still possible to store enough data at a reasonable price.
> 
> You can get more space by adding more users, 5TB per user each for around $20 per month.
> 
> With 5+ users it is possible to request more storage from support, 5TB per user every 90 days.
> 
> So 25TB every 3 months extra, which should be easily enough to archive multiple streamers for under $100 per month.
> 
> You can further drop the cost by "archiving" these extra users, which saves around 2/3, so roughly down to $60 per month total for 5.

If you want vods to be archived indefinitely, it's unfortunately not happening here by the looks of it.

**Comment by TimIsOverpowered** [comment]
> It is still possible to store enough data at a reasonable price.
> 
> You can get more space by adding more users, 5TB per user each for around $20 per month.
> 
> With 5+ users it is possible to request more storage from support, 5TB per user every 90 days.
> 
> So 25TB every 3 months extra, which should be easily enough to archive multiple streamers for under $100 per month.
> 
> You can further drop the cost by "archiving" these extra users, which saves around 2/3, so roughly down to $60 per month total for 5.

I have already researched this back in July. It would not be feasible to do. 

It is a pain requesting more storage because 99% of the time, they will not give you extra storage based on other people's experiences. Even when you do get accepted, you don't get nearly enough especially if you have a backlog of archived data. (300TB+)

The money cost is absurd when it comes to archiving video files. If XQC wants to pay for that, then it would be a different story. AFAIK, there hasn't been any interest.

**Comment by VirtusB** [comment]
Hi Op, have all the vods been deleted? If not I would be able to download all xQc vods+chat and store 80TB locally as a backup, and provide hosting for around 20TB of that. 

If it's ~560 vods, wouldn't that be around 11TB or 12TB?

300TB must include a lot of other streamers...?

**Comment by mendoxei** [comment]
Shot in the dark here, did anyone back up the vods? I would've downloaded it if i knew they were going to be deleted :(
